### ISSUE TITLE
Do you have plans to update the build?

### ISSUE THREAD

**Issue by JoeChapman** [justinribeiro/dockerfiles#15]

**Comment by justinribeiro** [comment]
Hi! I just pushed a new deb from the Chromium tip and pushed a build;the deb pushed to GCS doesn't trigger the docker build on hub (my fault, I need to enable the build trigger in my push script).

**Comment by alpeware** [comment]
FYI 

@JoeChapman if you want an image with the latest build, you can check out this image built off the trunk. It's automatically updated multiple times a day and includes tags for each new rev.

https://hub.docker.com/r/alpeware/chrome-headless-trunk/

**Comment by justinribeiro** [comment]
@JoeChapman As @alpeware mentioned, if you want off tip, Alpeware's container is the way to go (cheers for doing that by the way! 👍) 

I've had a lot of asks to move this to track stable once M59 lands and add SECCOMP, so that's the state this container will be in at this point (it's pointed at M59 in beta now and has SECCOMP support now).
