### ISSUE TITLE
Lighthouse docker image fix

### ISSUE THREAD

**Issue by TAnas0** [justinribeiro/dockerfiles#45]
Hello,

I had trouble getting started with the Lighthouse docker image.

Running an audit in the docker image goes fine but fails when saving the HTML report to `/home/chrome/reports` inside of the docker images with due to permissions with the message:

```
  status Evaluating: Document avoids plugins +1ms
  status Evaluating: Document has a valid `rel=canonical` +0ms
  status Evaluating: Page is mobile friendly +1ms
  status Evaluating: Structured data is valid +1ms
  status Generating results... +0ms
  ChromeLauncher Killing Chrome instance 23 +40ms
Runtime error encountered: EACCES: permission denied, open '/home/chrome/reports/justinribeiro.com_2019-03-16_15-52-57.report.html'
Error: EACCES: permission denied, open '/home/chrome/reports/justinribeiro.com_2019-03-16_15-52-57.report.html'
```

The directory `/home/chrome/reports` inside of the docker container is still owned by root. The command `chown -R chrome:chrome /home/chrome` in the Dockerfile does not seem to register, as `ls -la /home/chrome` shows:
```bash
drwxr-xr-x 3 chrome chrome 4096 Oct 18 05:49 .
drwxr-xr-x 1 root   root   4096 Oct 18 05:49 ..
drwxr-xr-x 2 root   root   4096 Mar 16 15:34 reports
```
This is probably related to this [SO question](https://stackoverflow.com/questions/26145351/why-doesnt-chown-work-in-dockerfile).

On the other hand, I went around and toyed around with the [Dockerfile](https://github.com/justinribeiro/dockerfiles/tree/master/lighthouse) and found out the building it fails at step 5 `npm install -g lighthouse` because NPM is missing.
This is because NPM is not shipped by default with Nodejs in Debian and need to be specified explicitly.

This, surprisingly, solves of course, the error about NPM being missing *AND* the above mentioned permissions error and `ls -la /hone/chrome` from inside the new built image outputs:

```
drwxr-xr-x 3 chrome chrome 4096 Mar 16 16:06 .
drwxr-xr-x 1 root   root   4096 Mar 16 16:06 ..
drwxr-xr-x 2 chrome chrome 4096 Mar 16 16:06 reports
```

**Comment by justinribeiro** [comment]
Saving the file to your local folder based on the bindmount depends on several factors, particularly how user namespacing and re-mapping works due to the use of the non-privileged chrome user. For instance, this is a run on my local from a build from master of the lighthouse image:

![image](https://user-images.githubusercontent.com/643503/69170788-8713d580-0aaf-11ea-9714-2a03c9fdf6cf.png)

Note that the container has a bindmount to lh-test, and after a lighthouse run the file is available in the local filesystem for viewing. You'll also note that inside the container, the chown'ed perms have been remapped, yet no errors occur on the save to the writable bind.

For more information on this and various permissions, see resources such as [Isolate containers with a user namespace](https://docs.docker.com/engine/security/userns-remap/) or [Use Linux user namespaces to fix permissions in docker volumes](https://www.jujens.eu/posts/en/2017/Jul/02/docker-userns-remap/)
